version: '3.11'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file: 
      - .env

  worker:
    build: .
    command: celery -A celeryconfig worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file: 
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
